#pragma once

// From glfw3.h
#define TINYVR_MOUSE_BUTTON_1         0
#define TINYVR_MOUSE_BUTTON_2         1
#define TINYVR_MOUSE_BUTTON_3         2
#define TINYVR_MOUSE_BUTTON_4         3
#define TINYVR_MOUSE_BUTTON_5         4
#define TINYVR_MOUSE_BUTTON_6         5
#define TINYVR_MOUSE_BUTTON_7         6
#define TINYVR_MOUSE_BUTTON_8         7
#define TINYVR_MOUSE_BUTTON_LAST      TINYVR_MOUSE_BUTTON_8
#define TINYVR_MOUSE_BUTTON_LEFT      TINYVR_MOUSE_BUTTON_1
#define TINYVR_MOUSE_BUTTON_RIGHT     TINYVR_MOUSE_BUTTON_2
#define TINYVR_MOUSE_BUTTON_MIDDLE    TINYVR_MOUSE_BUTTON_3